<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terjadi pelanggaran syarat kredit  2 _73fba9</name>
   <tag></tag>
   <elementGuidId>ca14ded5-82f3-47de-b6d0-bc8d0e8fa1fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbA_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbA_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bea5574-209d-4c93-90f7-73f4de89aa1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>64675f5f-331a-4d3c-9181-8770f7a87758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox_A</value>
      <webElementGuid>9ab2fdea-1b7e-472c-8ca4-bcef83d9e602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attr_unique</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>165531c1-cf15-4456-a96e-14c07c544cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbA_1</value>
      <webElementGuid>2d64f7c2-135f-49f0-b0f8-9018d768063b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbA_1</value>
      <webElementGuid>50bd9e83-4c1f-4aaf-b6b3-7cbdb49ec898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1686491f-32fe-4c69-ba62-101396b37dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbA_1&quot;)</value>
      <webElementGuid>a1b41a0d-7afc-490d-b920-8fdc3428cb36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbA_1']</value>
      <webElementGuid>edd1a729-afa4-4d7a-a5b4-c703ccf31cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-cbA_1']/span/input</value>
      <webElementGuid>34fec3a0-91b8-4e58-8e4c-ec1b48e8b0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/center/div/span/input</value>
      <webElementGuid>7aa5dfca-97f5-4635-a785-7d845cbf15c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cbA_1' and @name = 'cbA_1']</value>
      <webElementGuid>ee898934-7847-434d-9bc4-189a574b9f01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
