<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terjadi pelanggaran syarat kredit  2 _a573b7</name>
   <tag></tag>
   <elementGuidId>2be620f4-0f05-4228-8460-c12a2127c0fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ketA_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ketA_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8bdbfdc-e464-41d0-883e-87d6eb21bb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7aeb18a-35a2-4016-b0bd-ac9a5ec50bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ket_penilaian_A_inp</value>
      <webElementGuid>fe262d84-d3c6-47d0-bb7b-f09b8c3e59d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ketA_1</value>
      <webElementGuid>3eb87558-040d-495f-9cbb-54fa0ff01186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ketA_1</value>
      <webElementGuid>1299ceda-5d47-4c17-bf90-78e0e3cce101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Default Keterangan</value>
      <webElementGuid>528774b4-c36a-4de3-984d-1c95a522f06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ketA_1&quot;)</value>
      <webElementGuid>46c225ab-d060-400d-a03b-847c3797138e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ketA_1']</value>
      <webElementGuid>d10c1f56-692d-4286-8e4c-f993d555d8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myform']/table/tbody/tr[2]/td[4]/center/input</value>
      <webElementGuid>5cb14a85-cf0c-480c-9863-50074929154c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/center/input</value>
      <webElementGuid>23e390f0-b399-4511-86bd-3af27ff5460d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ketA_1' and @name = 'ketA_1']</value>
      <webElementGuid>3e6fc01c-4504-4ca0-84aa-3596c9dccb59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
