<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Profit margin turun  25 dari periode _977735</name>
   <tag></tag>
   <elementGuidId>171945a4-a924-4b3c-b07d-f14e4acf6d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbB_6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbB_6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03cbf99a-f540-4bf4-961a-40ed7b39c8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c912da77-167d-4b0a-9615-6da6fce473f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox_B</value>
      <webElementGuid>cddfe76d-88f0-4665-87ed-0e5fd1faf92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attr_unique</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>1113e373-6159-4860-b824-f79ec8603d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbB_6</value>
      <webElementGuid>168c6b6a-954f-42a1-b0fb-7a40d235a433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbB_6</value>
      <webElementGuid>3ee12209-265d-4856-b0ec-02ec2f274f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cc1bd620-d84a-4a55-a8c9-2b2e7a7c25d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbB_6&quot;)</value>
      <webElementGuid>66c8de8a-bfe5-4743-8125-b978d4586328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbB_6']</value>
      <webElementGuid>8d5efc60-f16d-409c-9f03-d4d8cb3b4866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-cbB_6']/span/input</value>
      <webElementGuid>0da6dfd8-c850-4b1f-a267-b54c526afd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[7]/td[3]/center/div/span/input</value>
      <webElementGuid>6c644038-f017-4e28-a65f-131042df15f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cbB_6' and @name = 'cbB_6']</value>
      <webElementGuid>5acc58c6-7fc9-4be1-b68e-4b776aa5b57d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
