<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kemampuan debitur dalam membayar kewa_341e21</name>
   <tag></tag>
   <elementGuidId>7f3a6725-28f0-43fe-b015-d1081e21b0a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbB_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbB_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2901289d-ad26-4ca7-9d94-5e081e920f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>709a8d67-22bc-421a-9949-6f67976ec81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox_B</value>
      <webElementGuid>7f1b1b81-fe67-4c77-ad87-5ccc689fa282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attr_unique</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6f336122-4a7c-4b29-9757-7f92652a91ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbB_2</value>
      <webElementGuid>168f3c17-b788-4892-919b-da43efd47afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbB_2</value>
      <webElementGuid>2b3883fb-ce1f-48f1-b9f1-1c30ff6a400e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f5641fd9-a681-42ae-998e-5dfb38e95d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbB_2&quot;)</value>
      <webElementGuid>d4f184a5-13d2-4cd4-9733-71591739572a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbB_2']</value>
      <webElementGuid>7b92a97c-0223-4705-bf83-718d9e7a414d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-cbB_2']/span/input</value>
      <webElementGuid>6aa6e69c-e818-4ee5-a40f-64d1f618e8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[3]/td[3]/center/div/span/input</value>
      <webElementGuid>69803004-937a-4ec3-a87d-d9ee70ac0309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cbB_2' and @name = 'cbB_2']</value>
      <webElementGuid>a8f6df7e-393e-436c-8399-9450da3ab5a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
