<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perubahan rating debitur (CRR) menjad_0dd308</name>
   <tag></tag>
   <elementGuidId>4b1472c4-ba5f-45a6-a3b4-cb3fba8855e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbA_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbA_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ed3bdf5-f4c8-4e35-80a4-9ef458ef4478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b68167e3-ee92-4732-b691-737a029d6afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox_A</value>
      <webElementGuid>c22accc3-53c9-4dfb-8022-b539685fb707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attr_unique</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f95fdf73-fdbc-4b6b-8146-230142232b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbA_0</value>
      <webElementGuid>fd65e265-07b1-412c-a70f-2cec36a5fe14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbA_0</value>
      <webElementGuid>c1145a28-dda4-4249-89cc-193b20ed5720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d4e959c0-6dd1-401a-9ed1-1ea472570953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbA_0&quot;)</value>
      <webElementGuid>352a6eb5-9393-4afb-8588-a7126b6915ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbA_0']</value>
      <webElementGuid>c85be2a8-1c82-4dc7-941c-e1ae159962f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-cbA_0']/span/input</value>
      <webElementGuid>d2d1b0f9-3c15-4d7d-84f4-2754ff5100a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>6fe0cf80-01c7-43e5-811c-bd7fb68f1aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cbA_0' and @name = 'cbA_0']</value>
      <webElementGuid>9d2c6dbb-b988-40e0-8ac8-a3a2f4dc40da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
