<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_NPW agunan masih mengcover pinjama_6f5880</name>
   <tag></tag>
   <elementGuidId>24fee182-e479-460e-b373-639cae73eb82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ket_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6caf2301-7a44-4a80-982b-e9de4f6a4b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_4</value>
      <webElementGuid>0e1a2076-bb80-472c-8b82-c3e9da2bcde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_4</value>
      <webElementGuid>85610c8b-d60f-49fb-af25-a716e73147ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NPW agunan masih mengcover pinjaman PTPN X di Bank BRIsf</value>
      <webElementGuid>37f9de69-4126-43d4-9a7e-ebfc7dbaf490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_4&quot;)</value>
      <webElementGuid>4b82fce2-2b5e-4131-9a8f-b419ec9ea78e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ket_4']</value>
      <webElementGuid>b6251e15-0647-4fde-bda8-c28deea17fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[10]/td/textarea</value>
      <webElementGuid>99cbd7c0-765a-4e30-a7df-d41a2dbdf703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analisis Agunan Sebagai Sumber Pembayaran'])[1]/following::textarea[1]</value>
      <webElementGuid>44f8f8ae-c834-42d0-ac93-d16bc9485e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdsf'])[3]/following::textarea[1]</value>
      <webElementGuid>842f3d03-e8c4-405d-9e8c-3fcccb97b37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a717eb4c-1760-4b1f-8446-18319dd869ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e7f4f85d-5ba6-454a-a212-ce9b6b0ce50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NPW agunan masih mengcover pinjaman PTPN X di Bank BRIsf']/parent::*</value>
      <webElementGuid>c2d9d6c8-70df-4c81-805e-2a169bd88abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/textarea</value>
      <webElementGuid>6d568b3b-5347-4bb4-ab2e-ade76ac27a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ket_4' and @name = 'ket_4' and (text() = 'NPW agunan masih mengcover pinjaman PTPN X di Bank BRIsf' or . = 'NPW agunan masih mengcover pinjaman PTPN X di Bank BRIsf')]</value>
      <webElementGuid>2ccbedc6-115f-48f1-bd5e-0ec1d90acbc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
