<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_102550100</name>
   <tag></tag>
   <elementGuidId>8fb0398e-e419-47ed-bcd4-904f8a45156b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='DataTables_Table_0_length']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;DataTables_Table_0_length&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5023b493-ba66-4eca-8d77-8b61a0f3f5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a5573588-93d2-4663-a10e-5ddc0f21fcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataTables_Table_0_length</value>
      <webElementGuid>c1bdbd1c-e027-444d-8f4d-a8f028bde670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>6fd9c400-b99d-4eb3-9efb-49be39453ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100</value>
      <webElementGuid>eb6c42c8-90af-4590-944a-a108f216549c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0_length&quot;)/label[1]/select[1]</value>
      <webElementGuid>3ce3743b-c34a-45ff-bc95-d87238ad07fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='DataTables_Table_0_length']</value>
      <webElementGuid>651d6772-1493-4925-a792-72cd06b8ec4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataTables_Table_0_length']/label/select</value>
      <webElementGuid>12e4ec1c-930b-4177-92ac-703b50f94390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspect List'])[1]/following::select[1]</value>
      <webElementGuid>714f5fe9-4d18-4800-8d7b-f7333ee8a567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::select[1]</value>
      <webElementGuid>a198818f-b3dd-460a-ab04-c04e7ec247c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::select[1]</value>
      <webElementGuid>3131cd32-fb37-4dca-987f-e85538fb8174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>96cbbdf7-a481-47e7-9541-c83f6c40cbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'DataTables_Table_0_length' and (text() = '102550100' or . = '102550100')]</value>
      <webElementGuid>47d2f9a5-d70b-4110-8fae-9f725f9c8815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
