<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Analisis Agunan Sebagai Sumber Pembayaran</name>
   <tag></tag>
   <elementGuidId>31d1130e-841d-48ac-a958-2d947ef14bac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[9]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a756999b-0eef-4aee-9058-e0f7fa7141de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Analisis Agunan Sebagai Sumber Pembayaran</value>
      <webElementGuid>4f84c1ec-29ac-4a14-b9ce-4bd87ee08eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;box&quot;]/div[@class=&quot;well fix&quot;]/form[1]/table[@class=&quot;table&quot;]/tbody[1]/tr[9]/td[1]</value>
      <webElementGuid>e8fc6f52-4b8c-4ebe-817a-a5cf6dbc62d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[9]/td</value>
      <webElementGuid>a64eb96e-adbd-489d-917a-bb526c08f3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prospek Usaha Ke Depan'])[1]/following::td[2]</value>
      <webElementGuid>185c4eac-434a-4835-af45-6d63bd8b4ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTPN X menjadi bagian restrukturisasi PTPN Group'])[1]/following::td[3]</value>
      <webElementGuid>2a75de59-da91-41d9-9a6a-09bfeebdd988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPW agunan masih mengcover pinjaman PTPN X di Bank BRI'])[1]/preceding::td[1]</value>
      <webElementGuid>36509575-3483-4151-8867-54b1ea708d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td</value>
      <webElementGuid>bc1b9e68-5f9c-41df-827a-6915a780a512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Analisis Agunan Sebagai Sumber Pembayaran' or . = 'Analisis Agunan Sebagai Sumber Pembayaran')]</value>
      <webElementGuid>0358baa8-6a6c-405e-87f2-8b3406a59a5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
