<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Prosepek Usaha Ke Depan</name>
   <tag></tag>
   <elementGuidId>ff88b7e5-7c64-4ff5-b487-f6f3a54e38da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ket_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9d10cbc9-6c69-434d-9914-c2c127b5b90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_3</value>
      <webElementGuid>2166c836-ae69-4f80-9fc4-1758ff0aadc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_3</value>
      <webElementGuid>e76aadd0-d0d9-4993-8a61-4ec30973189e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Supply Gula untuk kebutuhan domestik pada tahun 2020 masih lebih sedikit dibandingkan demand atas Gula. selisih antara demand dan supply ini dipenuhi dari impor raw sugar yang dilakukan oleh pemerintah setiap tahunnya demi memenuhi kebutuhan gulan dalam n</value>
      <webElementGuid>66b9090b-54fc-4531-b2e1-172c32d9cfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_3&quot;)</value>
      <webElementGuid>49c4befa-91bb-4cbe-9cb5-b0140c07df80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ket_3']</value>
      <webElementGuid>01ee58d3-a666-4bf0-9bef-9355804cc698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[8]/td/textarea</value>
      <webElementGuid>e272986f-56e5-48ce-b8a1-7344eacd2414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prospek Usaha Ke Depan'])[1]/following::textarea[1]</value>
      <webElementGuid>76a0d78c-38ce-4863-9451-ed50adba1051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTPN X menjadi bagian restrukturisasi PTPN Group'])[1]/following::textarea[1]</value>
      <webElementGuid>856af1e9-494d-4841-970e-641f9ac90ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analisis Agunan Sebagai Sumber Pembayaran'])[1]/preceding::textarea[1]</value>
      <webElementGuid>05703577-5f9c-4100-8fe1-0e1afdb3cb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPW agunan masih mengcover pinjaman PTPN X di Bank BRI'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e6ae5a78-cd90-4534-a2bb-234559fa6cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/textarea</value>
      <webElementGuid>e5a6bba5-bdd1-4040-a6e1-54d9324dd812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ket_3' and @name = 'ket_3' and (text() = 'Supply Gula untuk kebutuhan domestik pada tahun 2020 masih lebih sedikit dibandingkan demand atas Gula. selisih antara demand dan supply ini dipenuhi dari impor raw sugar yang dilakukan oleh pemerintah setiap tahunnya demi memenuhi kebutuhan gulan dalam n' or . = 'Supply Gula untuk kebutuhan domestik pada tahun 2020 masih lebih sedikit dibandingkan demand atas Gula. selisih antara demand dan supply ini dipenuhi dari impor raw sugar yang dilakukan oleh pemerintah setiap tahunnya demi memenuhi kebutuhan gulan dalam n')]</value>
      <webElementGuid>b27c2729-662e-48f1-b05f-26c303bd4e38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
