<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Analisis Agunan Sebagai Sumber Pembayaran</name>
   <tag></tag>
   <elementGuidId>672a2297-2dfd-4d9b-9542-09baa950fa4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ket_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ef854019-51b7-49fb-aadd-c562168671e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_4</value>
      <webElementGuid>b73c568d-562f-489d-acbe-01977ac53dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_4</value>
      <webElementGuid>8ca55491-0891-4ed4-8cc2-f945d165bf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NPW agunan masih mengcover pinjaman PTPN X di Bank BRI</value>
      <webElementGuid>cff73f29-6da5-4946-a59e-178af17e9efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_4&quot;)</value>
      <webElementGuid>ba920253-a427-4b34-87b3-4226598ab155</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ket_4']</value>
      <webElementGuid>8a2a8559-3376-4a30-b1e3-1dcc9a088fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[10]/td/textarea</value>
      <webElementGuid>540fe656-a2d0-4f65-a2f7-5481a299066b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analisis Agunan Sebagai Sumber Pembayaran'])[1]/following::textarea[1]</value>
      <webElementGuid>3869a5c5-592e-4c11-b5aa-ed73408694a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prospek Usaha Ke Depan'])[1]/following::textarea[2]</value>
      <webElementGuid>ff52ee8a-c017-4f4e-96e5-7dc9836e0430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b759e500-a440-4eb3-839b-f7a299c863fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::textarea[1]</value>
      <webElementGuid>60bd1fdd-1379-45a8-a76d-7253dbee411d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NPW agunan masih mengcover pinjaman PTPN X di Bank BRI']/parent::*</value>
      <webElementGuid>b37a8e84-da07-48d2-b4cb-e209f6ad197f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/textarea</value>
      <webElementGuid>cb6d59af-d41a-4caf-85ba-e262d06c1798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ket_4' and @name = 'ket_4' and (text() = 'NPW agunan masih mengcover pinjaman PTPN X di Bank BRI' or . = 'NPW agunan masih mengcover pinjaman PTPN X di Bank BRI')]</value>
      <webElementGuid>e2c432b3-f07b-4c20-ba32-4ba2eb2ff5a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
