<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Kemampuan Bayar Debitur</name>
   <tag></tag>
   <elementGuidId>00661c1e-31a6-433d-95e2-d2fc61132415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ket_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b3387909-cfa8-4a1e-a012-db1d58123938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_1</value>
      <webElementGuid>87d29276-b82f-4ab2-b5ff-9adfcf7c9707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_1</value>
      <webElementGuid>3af331ba-450a-47c5-be0b-090a973816de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PTPN X masih memiliki kemampuan membayar yang baik. atas cashflownya PTPN X dapat melunasi hutang di Bank BRI</value>
      <webElementGuid>2906e33f-5c8d-4a18-8d28-b63e35af2860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_1&quot;)</value>
      <webElementGuid>ce541c8e-3976-4680-86ed-4257b617432f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ket_1']</value>
      <webElementGuid>00ede3f5-de64-474c-ac4c-24332543bd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[4]/td/textarea</value>
      <webElementGuid>d8b72518-61e7-41ae-9113-41c5a82fc6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kemampuan Bayar Debitur'])[1]/following::textarea[1]</value>
      <webElementGuid>232fc8ae-811a-49d2-9597-cd0af3e67f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi Usaha Saat Ini'])[1]/following::textarea[2]</value>
      <webElementGuid>85e40a87-f682-4828-b1e7-494574ef57b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyebab Kredit Bermasalah'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e766c7f7-8181-40c6-8b58-169cc8144c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTPN X menjadi bagian restrukturisasi PTPN Group'])[1]/preceding::textarea[1]</value>
      <webElementGuid>abbec3dd-8b33-4e47-92fe-825c1f8859bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PTPN X masih memiliki kemampuan membayar yang baik. atas cashflownya PTPN X dapat melunasi hutang di Bank BRI']/parent::*</value>
      <webElementGuid>102ca46a-03e4-494a-aa14-36d5a3de54b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/textarea</value>
      <webElementGuid>2e199f97-118e-449f-9a18-58d73ee60c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ket_1' and @name = 'ket_1' and (text() = 'PTPN X masih memiliki kemampuan membayar yang baik. atas cashflownya PTPN X dapat melunasi hutang di Bank BRI' or . = 'PTPN X masih memiliki kemampuan membayar yang baik. atas cashflownya PTPN X dapat melunasi hutang di Bank BRI')]</value>
      <webElementGuid>7c6ae760-7c73-4f11-b8e8-e2b28b832981</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
