<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Penyebab Kredit Bermasalah</name>
   <tag></tag>
   <elementGuidId>22eaef53-2af4-4051-a7bb-4eb25c790394</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ket_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6618b7af-0396-4760-9e8b-2ec1fe8033e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_2</value>
      <webElementGuid>6fb3fc25-6728-4cd2-9abe-617e80e8f78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_2</value>
      <webElementGuid>a481a0cc-6a04-41ed-9620-3651cd978640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PTPN X menjadi bagian restrukturisasi PTPN Group</value>
      <webElementGuid>0147d46d-0abb-41b8-8b4e-161e1a25118b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_2&quot;)</value>
      <webElementGuid>457f8483-4b0a-406d-87aa-c14d06e81bca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ket_2']</value>
      <webElementGuid>b9afd4d9-b2cb-42cf-aa1b-12340dcd1f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[6]/td/textarea</value>
      <webElementGuid>7a25847e-8002-48e0-94d3-df164a0296af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyebab Kredit Bermasalah'])[1]/following::textarea[1]</value>
      <webElementGuid>9fb3888a-3a8e-4989-b9d6-c67028b19c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kemampuan Bayar Debitur'])[1]/following::textarea[2]</value>
      <webElementGuid>627abfa5-3b29-4a2c-9338-a5bd47253f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prospek Usaha Ke Depan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e95397d4-86b9-4c0f-8ce7-12d991732c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analisis Agunan Sebagai Sumber Pembayaran'])[1]/preceding::textarea[2]</value>
      <webElementGuid>4cab8ef3-2284-4377-b34b-feb1a864ef42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PTPN X menjadi bagian restrukturisasi PTPN Group']/parent::*</value>
      <webElementGuid>a03836d2-dfaf-436e-acd7-46aab8ff038d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/textarea</value>
      <webElementGuid>7ac66091-2e83-4593-9d9b-9c09c6e7a479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ket_2' and @name = 'ket_2' and (text() = 'PTPN X menjadi bagian restrukturisasi PTPN Group' or . = 'PTPN X menjadi bagian restrukturisasi PTPN Group')]</value>
      <webElementGuid>d29aaa35-627e-4d14-8841-5f6d15aa9776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
