<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Maintain Agunan</name>
   <tag></tag>
   <elementGuidId>8eee53c7-0653-49e0-a6cc-22aa9bf21679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;maintain_agunan('PJ78102');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad8d8a95-185a-4658-990e-b4f3cd02326e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>05db2b75-67f1-4bb5-b3d2-ed0d41f4ab0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>maintain_agunan('PJ78102');</value>
      <webElementGuid>400dba05-0171-4c6a-9d40-6080b91ddfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Maintain Agunan</value>
      <webElementGuid>566314f9-f829-4a89-a4ff-315207f42c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblagunan&quot;)/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>da20c403-9b1a-480c-ab66-1a9024cbd3f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;maintain_agunan('PJ78102');&quot;]</value>
      <webElementGuid>3222c832-ea0f-45ea-93ec-3cb97da0b183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tblagunan']/button</value>
      <webElementGuid>cc7b9942-500b-4521-bd76-0095fbbbcf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Maintain porsi nilai agunan dengan menekan tombol ', '&quot;', '+ Maintain Agunan', '&quot;', '')])[1]/following::button[1]</value>
      <webElementGuid>72439f5b-864e-4a66-b452-ff4e59626a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Pengisian :'])[1]/following::button[1]</value>
      <webElementGuid>0d75db26-7c39-474e-b005-aad19a904dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::button[1]</value>
      <webElementGuid>c293882c-13e3-419f-92a1-c84e59e12a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maintain Agunan']/parent::*</value>
      <webElementGuid>3d40f888-2fe8-4a7c-b8db-6d094530d0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>35454a46-6fe3-4d35-bf3b-d97ed304dfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Maintain Agunan' or . = ' Maintain Agunan')]</value>
      <webElementGuid>cc818976-c04b-4a95-a04b-aa10f3d3ab40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
