<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Data</name>
   <tag></tag>
   <elementGuidId>e71429af-6604-4645-858a-8f43184fbc5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tambah_suspect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tambah_suspect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63c85521-ec69-4e2b-9c53-ac26ca2608b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>9b1cd970-c08f-4f52-a4fe-0a22d4345be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tambah_suspect</value>
      <webElementGuid>f293d131-daec-427c-be95-2eb74e541042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah Data</value>
      <webElementGuid>556152ed-93f7-4911-9ac3-5f083d805cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tambah_suspect&quot;)</value>
      <webElementGuid>18bd640a-db5a-43a8-8533-1ceb8c4dc7ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tambah_suspect']</value>
      <webElementGuid>52b33c0c-f534-4e2c-b3a4-cee8ab76472a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/button</value>
      <webElementGuid>d78e1e04-7d9b-4d57-8524-19ec1bdeafe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Debitur CKPN'])[1]/following::button[1]</value>
      <webElementGuid>cebd9120-66ab-44c0-81c3-bfd1f01243be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Rek. Pinjaman'])[1]/following::button[1]</value>
      <webElementGuid>1593d784-526a-498a-94b2-51b29ce386e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::button[1]</value>
      <webElementGuid>b6c7f010-32f7-4cea-9169-7d3edc6666d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Data']/parent::*</value>
      <webElementGuid>59762b70-1fcb-495b-b96c-cdf9d6653891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>07fe9a96-0b85-4333-a124-842e9f14ded2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tambah_suspect' and (text() = ' Tambah Data' or . = ' Tambah Data')]</value>
      <webElementGuid>d8dd9f7d-183e-4190-8c20-8132b1edf40e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
