<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ket</name>
   <tag></tag>
   <elementGuidId>7ee91bfc-526d-4d1f-a212-9e9e7bedc915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ketAddAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ketAddAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27300733-1696-4388-914e-a4cd99d37795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a1ba008-bd81-4ad1-980b-6437fa1a005b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket</value>
      <webElementGuid>ac583f45-d1da-4421-8f49-9f43a95a3252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ketAddAccount</value>
      <webElementGuid>5eeae49a-ad66-4603-ae98-1c2d2b3948f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ketAddAccount&quot;)</value>
      <webElementGuid>51d54114-415c-4cac-9aa5-75dfe7686464</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ketAddAccount']</value>
      <webElementGuid>ffb26b64-5739-430e-9eb6-c7e3efa77b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ketPengajuan']/tbody/tr/td[3]/input</value>
      <webElementGuid>35de880c-7c80-4b68-8ce9-f36b1210e0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>118be7fa-ea0d-4258-b8e6-e0817fea27c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ket' and @id = 'ketAddAccount']</value>
      <webElementGuid>dc767f9a-d9e7-40c2-a4c4-db75a8783755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
