<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cari Berdasarkan CIF_inpSearch</name>
   <tag></tag>
   <elementGuidId>b6e5dcf7-1cb9-4d7d-9fe3-14082648be48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inpSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inpSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40cbaf7f-47b5-4ada-b396-c8e64493a737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8cfaf160-7bf5-4582-b0bb-8e5173166409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inpSearch</value>
      <webElementGuid>d0a31791-a316-4c39-aeb7-8798be1f6f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpSearch&quot;)</value>
      <webElementGuid>ee83958e-6762-441a-a36d-f40098bb98d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inpSearch']</value>
      <webElementGuid>323a227d-ad39-4636-b6e0-4d925b981e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addModal']/div/div/form/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>26ea5202-b07c-401b-8e16-bd180b1b9b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>ef89ecd4-e975-4e90-95b2-b0a79be2cf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inpSearch']</value>
      <webElementGuid>4e6d7381-bc3a-4310-a458-d649cdd63c3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
