<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perubahan rating debitur (CRR) menjad_b0e5ae</name>
   <tag></tag>
   <elementGuidId>5b0f0cb8-6e74-4163-9e91-7530c0fcba4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ketA_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ketA_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9097211-3ef5-4e8c-8ba1-53825e7e2243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa1330ce-75dc-4c6f-af84-b8f254725aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ket_penilaian_A_inp</value>
      <webElementGuid>df51d981-39f8-4344-a852-2227167ae46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ketA_0</value>
      <webElementGuid>90b202a5-aab2-4f87-bf52-b2513be40bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ketA_0</value>
      <webElementGuid>a4987607-10da-4492-84a7-0f37850071d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Default Keterangan</value>
      <webElementGuid>5ae6a72d-82c2-42fc-ada6-24c9d0c5eef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ketA_0&quot;)</value>
      <webElementGuid>8db2cd9d-3ba3-4966-ab28-040a14b0daa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ketA_0']</value>
      <webElementGuid>2078b21a-28e9-4281-ade1-6f66a70397b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myform']/table/tbody/tr/td[4]/center/input</value>
      <webElementGuid>be5587f3-e653-4c35-97fe-ad0ec622830b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/input</value>
      <webElementGuid>7520389e-a3eb-47c9-8cc5-91b1e63c52a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ketA_0' and @name = 'ketA_0']</value>
      <webElementGuid>f7de7bf4-a79d-4ecf-ba65-450f4ed38c69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
