<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>d815b91e-7f8d-4c39-946f-3b75e7db9ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uniform-quest3op1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uniform-quest3op1 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f61730a9-5eb7-4c38-9a6b-441ee8987fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniform-quest3op1&quot;)/span[1]</value>
      <webElementGuid>22a42a8c-9aad-4c59-ab3d-4dab1193632c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-quest3op1']/span</value>
      <webElementGuid>d2103742-6827-494a-9b54-2e55c8f409fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[3]//span[1]</value>
      <webElementGuid>6298b8ea-dad7-4f1a-a6fe-3b9de9a3df47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sesuai periode pembayaran yang telah ditentukan'])[1]/following::span[1]</value>
      <webElementGuid>c89cc7cb-4330-40e3-9dea-e20a49d7d185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[3]/preceding::span[1]</value>
      <webElementGuid>afed8ecc-cda3-46c9-aec7-db05554793ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[4]/preceding::span[2]</value>
      <webElementGuid>947b3b03-bb34-4df7-9c2b-ef22414cb5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/label/div/span</value>
      <webElementGuid>d3e116b7-2ead-4352-a7d4-a8be1fab81a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
