<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>f92f0f1d-9dbe-4d83-ad8d-f59f7f19be58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uniform-quest3op2']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uniform-quest3op2 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>69116907-035b-4034-9b06-60c73d493d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniform-quest3op2&quot;)/span[1]</value>
      <webElementGuid>e62cd881-c21b-4d0b-9f68-38ae85d38fa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-quest3op2']/span</value>
      <webElementGuid>c94556c3-9907-480c-844a-0df02f806f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[3]//span[1]</value>
      <webElementGuid>56ad24af-1d65-4a22-80a2-545b46118be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[3]/following::span[1]</value>
      <webElementGuid>80c99bb6-9dfa-472a-a402-40f9e29762bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[4]/preceding::span[1]</value>
      <webElementGuid>6ef03504-c4c5-42d3-a5ac-3e3ee40736ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[4]/preceding::span[2]</value>
      <webElementGuid>103353bb-448e-4895-aed8-c84ca59ae925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/label[2]/div/span</value>
      <webElementGuid>f644e435-707c-4fcb-b01c-49fcefbf3098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
