<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>4ea13182-2939-4d84-abf2-16d1f85ff497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uniform-quest4op1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uniform-quest4op1 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>890fec1f-3469-4617-82ed-99259967980d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniform-quest4op1&quot;)/span[1]</value>
      <webElementGuid>aee52eb6-28a1-4688-8b90-9b88c54150ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-quest4op1']/span</value>
      <webElementGuid>6654ce0e-76b6-48d3-be41-e2c619735c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[4]//span[1]</value>
      <webElementGuid>31d0793a-e48f-4532-8fe4-7070e0f1573f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[3]/following::span[1]</value>
      <webElementGuid>52f4acf9-4b37-40eb-9b5c-da20bce3a921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[4]/preceding::span[1]</value>
      <webElementGuid>65ffd8f4-1fea-4927-8f13-6ba7f92f679b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Defered'])[1]/preceding::span[2]</value>
      <webElementGuid>3241bd34-590c-46fd-af05-12007fa72338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/label/div/span</value>
      <webElementGuid>fc99c928-3d8e-4295-9b53-78414a27ff7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
