<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>f6aab034-b8d1-4b15-af9e-935574b493bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uniform-quest4op2']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uniform-quest4op2 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5ddaeb0-817b-4714-9f43-78e30c905a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniform-quest4op2&quot;)/span[1]</value>
      <webElementGuid>89c2e259-0947-4d78-bf9e-028b2430b070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-quest4op2']/span</value>
      <webElementGuid>32aa2e66-2aa5-4720-906f-ae120f8dce25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[4]//span[1]</value>
      <webElementGuid>d00fadff-ca38-4330-b641-625412e841d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[4]/following::span[1]</value>
      <webElementGuid>b49546f7-b78a-4e5d-8c07-3d5acdd61e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Defered'])[1]/preceding::span[1]</value>
      <webElementGuid>3b98088d-9239-441c-bfe7-883cab84e158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Defered'])[1]/preceding::span[2]</value>
      <webElementGuid>d982b677-04c3-4c3d-8601-fe50e3c48b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/label[2]/div/span</value>
      <webElementGuid>6ab39b0f-e023-4308-973b-b13b2ff86dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
