<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__alasan</name>
   <tag></tag>
   <elementGuidId>acfe6755-4cd8-467f-b013-fc3d76ceb798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='alasan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alasan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c053cef6-f1d9-45c6-9472-360bfab05424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alasan</value>
      <webElementGuid>8ace6db8-1acc-4ced-af12-9d850f8cd988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alasan&quot;)</value>
      <webElementGuid>61a9beb1-3922-46ee-b5b2-bd2dd68b77d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='alasan']</value>
      <webElementGuid>5b574b52-821c-40a0-a765-64d2dcb138ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/div/div[2]/table/tbody/tr[2]/td[3]/textarea</value>
      <webElementGuid>01f159ca-ad0c-4aae-b269-a31e201ca92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8596ca16-3855-4532-8e9f-6544ecb73aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'alasan']</value>
      <webElementGuid>4e12f5c6-6dfa-4fae-8542-9a260bc509bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
