<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_asdsf_1_2</name>
   <tag></tag>
   <elementGuidId>46b31d8c-b578-499e-b03d-ebadf2e15e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ket_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7c529a72-9517-4b73-9461-505d3d4cd6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_3</value>
      <webElementGuid>d713d323-ffc4-4f0e-8f96-00070c7041a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_3</value>
      <webElementGuid>ca03848f-7c89-4b1a-898c-be9db7971b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>asdsf</value>
      <webElementGuid>df402b4e-f455-4bd9-99d5-5753ef84a73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_3&quot;)</value>
      <webElementGuid>7a364c70-5e53-43e2-a8d7-a8db8375575e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ket_3']</value>
      <webElementGuid>02443aa8-52a1-4723-a0d7-a3fe6f677c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[8]/td/textarea</value>
      <webElementGuid>212629e4-fbc4-40d5-bf0c-94aa2875cfa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prospek Usaha Ke Depan'])[1]/following::textarea[1]</value>
      <webElementGuid>803344ff-db0b-46ec-8b59-8b2330a8e4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdsf'])[2]/following::textarea[1]</value>
      <webElementGuid>97ab57f7-6e05-4c4d-b80c-e43ec5a95a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analisis Agunan Sebagai Sumber Pembayaran'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7f16463f-830b-4a33-bb39-830dd0082264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPW agunan masih mengcover pinjaman PTPN X di Bank BRIsf'])[1]/preceding::textarea[1]</value>
      <webElementGuid>1408b3f4-0852-46d4-91c8-336872a648b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/textarea</value>
      <webElementGuid>dd3ede25-a448-4ef9-826b-911e72057891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ket_3' and @name = 'ket_3' and (text() = 'asdsf' or . = 'asdsf')]</value>
      <webElementGuid>ce7ad94a-016d-408f-b337-6f22e59d27d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
