<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_asdsf_1</name>
   <tag></tag>
   <elementGuidId>c8e50d1c-54c9-4004-83fb-388f0e75bad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ket_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a3e3faef-0157-4434-a317-e6a569ca5f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_2</value>
      <webElementGuid>1039c090-1139-470c-8a91-289711fd4382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_2</value>
      <webElementGuid>5ff2cdaf-e21c-48d8-85f9-7f284cb75c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>asdsf</value>
      <webElementGuid>c2f2c618-ce00-4fb0-8d0a-68ee4dba1466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_2&quot;)</value>
      <webElementGuid>1c122e52-f9b1-4185-9338-11be39779a4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ket_2']</value>
      <webElementGuid>f7c49709-5cc9-494b-9595-a0b3c01cda6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[6]/td/textarea</value>
      <webElementGuid>f902d3ae-6614-4c6e-a5e4-b33f51f64b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyebab Kredit Bermasalah'])[1]/following::textarea[1]</value>
      <webElementGuid>43e4104c-72ab-4577-bd35-4e9bf8c667e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdsf'])[1]/following::textarea[1]</value>
      <webElementGuid>042373f6-a9c7-49b7-a30e-4692af72e433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prospek Usaha Ke Depan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>228517c3-ccc4-44c3-8d2a-6f12906cf3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdsf'])[3]/preceding::textarea[1]</value>
      <webElementGuid>05b200ab-ae48-4ac0-9369-f1d7306480be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/textarea</value>
      <webElementGuid>64f4e579-4b16-4d02-89da-1adbd5ec823a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ket_2' and @name = 'ket_2' and (text() = 'asdsf' or . = 'asdsf')]</value>
      <webElementGuid>cbf3646b-0763-42d5-bfc8-14f910303eee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
