<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_asdsaf</name>
   <tag></tag>
   <elementGuidId>492e3beb-0075-46e3-ac53-b5b8efa16480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ket_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f8509fd9-028f-44ff-9a7f-2323f3058c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_0</value>
      <webElementGuid>f878fe2d-5f62-4002-9a10-36a81488c2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_0</value>
      <webElementGuid>213417d6-97a7-47d5-8a29-48b6189fd80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>asdsaf</value>
      <webElementGuid>420ae730-a9c6-499b-be9c-ee57b0a6b25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_0&quot;)</value>
      <webElementGuid>cab21c04-3371-4145-a71e-f2944aa5aa77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ket_0']</value>
      <webElementGuid>48dc0f8f-d2c6-4907-a6d9-1f556bfdb356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[2]/td/textarea</value>
      <webElementGuid>4e9b6df8-34e8-45e4-a39c-698472b4b49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi Usaha Saat Ini'])[1]/following::textarea[1]</value>
      <webElementGuid>3b20651a-139b-42be-bb3a-e18cd28d50a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kemampuan Bayar Debitur'])[1]/preceding::textarea[1]</value>
      <webElementGuid>79c845a2-10e5-43a3-afa2-647a44a8dfa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdsf'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a0aecdae-571e-425d-b4c3-a53590df9e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='asdsaf']/parent::*</value>
      <webElementGuid>8769df86-812e-4ead-ae74-fb54d9aeb77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5373a505-d849-43a2-b1c0-b61435cc89cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ket_0' and @name = 'ket_0' and (text() = 'asdsaf' or . = 'asdsaf')]</value>
      <webElementGuid>d8c6c5b5-a275-4bb1-8cd3-51b3a44ce890</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
