<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_asdsf</name>
   <tag></tag>
   <elementGuidId>63326332-f00f-4f5e-b00b-54f5bd615b59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ket_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>220a2b4a-c422-4c8c-9607-2307264fa120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_1</value>
      <webElementGuid>3dbb1e74-9806-43d2-b650-de9e12e565cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_1</value>
      <webElementGuid>80d578af-8995-47ea-9ca8-7edeb0561cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>asdsf</value>
      <webElementGuid>3b7f2946-150c-444f-a82c-588c95511cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_1&quot;)</value>
      <webElementGuid>14e398e0-41aa-43c9-b13e-1b40b65134d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ket_1']</value>
      <webElementGuid>d04ccf34-bcd5-4b23-8a51-7934c0dfc7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/table/tbody/tr[4]/td/textarea</value>
      <webElementGuid>4c1ee6b1-c9a7-4346-8df2-9af69d5dbe95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kemampuan Bayar Debitur'])[1]/following::textarea[1]</value>
      <webElementGuid>0f8c2170-2050-4bbb-97e9-a05d86ac6c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdsaf'])[1]/following::textarea[1]</value>
      <webElementGuid>514c6d61-cbfd-487d-b5b1-61f5e82aa287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyebab Kredit Bermasalah'])[1]/preceding::textarea[1]</value>
      <webElementGuid>9e975384-b28f-45bc-be60-6190ac9f8a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdsf'])[2]/preceding::textarea[1]</value>
      <webElementGuid>868a153f-9be6-4f9f-9605-3470164fde6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='asdsf']/parent::*</value>
      <webElementGuid>74de7f57-05e2-475e-8108-f4d5656135f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/textarea</value>
      <webElementGuid>941b156c-f200-4e5e-baff-e219fbc94d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ket_1' and @name = 'ket_1' and (text() = 'asdsf' or . = 'asdsf')]</value>
      <webElementGuid>6dea7086-d0f0-4c3a-b4de-2199d97664f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
